### ISSUE TITLE
Improve Hand Class

### ISSUE THREAD

**Issue by ldehaine** [Cataboum/BlackJackProject#15]
### Current behavior

```
>>> hand_1 = Hand()
>>> hand_2 = Hand()
>>> hand_list = [hand_1, hand_2]
>>> hand_1 += Card(1)

>>> print(hand_list)
[Hand(card_list=[], is_dealer_hand=False), Hand(card_list=[], is_dealer_hand=False)]
>>> print(hand_1)
Hand(card_list=[Card(value = 1, name = ACE, color = HEARTS)], is_dealer_hand=False)
>>> # The variable hand_1 has been modified (reassigned), but the object referenced in hand_list has no changed
>>> # Is this what we would expect?
```
I made the `__add__` method of `Hand` so that it returns a different instance of `Hand` (that's actually a recent improvement, see PR #13
However, when we use the syntax `hand_1 += Card(1)` we may actually want the original `Hand` object to be modified.

### Wanted behavior

```
>>> hand_1 = Hand()
>>> hand_2 = Hand()
>>> hand_list = [hand_1, hand_2]
>>> hand_1 += Card(1)

>>> print(hand_list)
[Hand(card_list=[Card(value = 1, name = ACE, color = HEARTS)], is_dealer_hand=False), Hand(card_list=[], is_dealer_hand=False)]
>>> print(hand_1)
Hand(card_list=[Card(value = 1, name = ACE, color = HEARTS)], is_dealer_hand=False)
>>> Here we modified the object the `hand_1` variable points to, thus the change is reflected in the list object
```

This might seem like an obvious behavior but I prefer asking because this is not what happens for example when we do `a += 1` with `a` of `int` type, the variable is reassigned (since ints are immutable) so any list that was filled with this variable would not change.
This is however what happens with lists so it is definitely not an absurd behavior :
```
>>> l1 = [1, 2]
>>> l2 = [4, 5]
>>> c_l = [l1, l2]
>>> print(c_l)
[[1, 2], [4, 5]]
>>> l1 += [3]
>>> print(l1)
[1, 2, 3]
>>> print(c_l)
[[1, 2, 3], [4, 5]]
```

Tell me if this looks good to you 😉

**Comment by Hboni** [comment]
In the case of a game, if we create a `hand_list`, in case of a split for example, `Cards` will be add in both `Hands`, and it can be easier to add on `Hand` directly, impacting `hand_list`.
So I agree with your proposition !
