### ISSUE TITLE
Deck shuffling should not happen in the middle of a turn

### ISSUE THREAD

**Issue by ldehaine** [Cataboum/BlackJackProject#16]
### Current state

The Deck is shuffled when about 3/4th of the cards have been distributed... even if we're in the middle of a turn. Which implies that we could (although quite unlikely) draw 7 (or more) Aces of Hearts on the same turn although the Deck is supposed contain only **six** 52-cards decks.

### Proposed solution

I think that the Deck class itself is not supposed to know if we're in the middle of a turn or not. This would actually break MVC context since the Deck is part of the model whereas the notion of a game turn belongs to the Controller and View. So the shuffling needs to be handled by the controller.
What would make sense however is to set a bool flag in the Deck class telling that the Deck needs to be shuffled (i.e. we've reached 3/4th of the Deck's length). The controller will thus need to check the flag at the end of each turn and call the Deck's shuffle method if need be.

**Comment by Hboni** [comment]
I agree with your idea to improve `Deck` shuffling !
