### ISSUE TITLE
Button "_Carte_" blocked

### ISSUE THREAD

**Issue by Hboni** [Cataboum/BlackJackProject#42]
I tried to play, and when I click on the button "_carte_", the button stays pressed, even if finish the turn. (See picture attached)

![BlackJack_bug_carte](https://user-images.githubusercontent.com/27290853/66082202-ef434200-e569-11e9-9a05-c78fdab14c34.PNG)

**Comment by deplanty** [comment]
Yes, it was to make an example of the use of the `disable` method...
It is meant to be changed when the game structure is implemented (when clicking on a button disable the others / enable the others).

**Comment by deplanty** [comment]
Make the example within the `first_round`.

**Comment by Hboni** [comment]
Solved by #45
